// react-demo-app/src/components/CarForm.js
import { useState } from 'react';
import PropTypes from 'prop-types';

import './CarForm.css';

const emptyCarForm = () => ({
  make: '',
  model: '',
  year: 1900,
  color: '',
  price: 0,
});

export const CarForm = ({ buttonText, onSubmitCar }) => {

  const [ carForm, setCarForm ] = useState(emptyCarForm());

  const change = (e) => {
    setCarForm({
      ...carForm,
      [ e.target.name ]: e.target.type === 'number' ? parseInt(e.target.value) : e.target.value,
    });
  };

  const submitCar = () => {
    onSubmitCar({ ...carForm });

    setCarForm(emptyCarForm())
  };

  return (
    <form>
      <label>
        Make:
        <input type="text" name="make"
          value={carForm.make} onChange={change} />
      </label>
      <label>
        Model:
        <input type="text" name="model"
          value={carForm.model} onChange={change} />
      </label>
      <label>
        Year:
        <input type="number" name="year"
          value={carForm.year} onChange={change} />
      </label>
      <label>
        Color:
        <input type="text" name="color"
          value={carForm.color} onChange={change} />
      </label>
      <label>
        Price:
        <input type="text" name="price"
          value={carForm.price} onChange={change} />
      </label>
      <button type="button" onClick={submitCar}>{buttonText}</button>
    </form>    
  );

};

CarForm.defaultProps = {
  buttonText: 'Submit Car',
};

CarForm.propTypes = {
  buttonText: PropTypes.string.isRequired,
  onSubmitCar: PropTypes.func.isRequired,
};

// angular-demo-app/src/app/car-tool/components/car-form/car-form.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

import { NewCar } from '../../models/cars';

@Component({
  selector: 'app-car-form',
  templateUrl: './car-form.component.html',
  styleUrls: ['./car-form.component.css']
})
export class CarFormComponent implements OnInit {

  @Input()
  buttonText = "Submit Car";

  @Output()
  submitCar = new EventEmitter<NewCar>();  

  carForm!: FormGroup;
 

  constructor(private fb: FormBuilder) {

  }

  ngOnInit(): void {
    this.carForm = this.fb.group({
      make: '',
      model: '',
      year: 1900,
      color: '',
      price: 0,
    });
  }

  doSubmitCar() {
    this.submitCar.emit(this.carForm.value as NewCar);

    this.carForm.reset();
  }

}

<form [formGroup]="carForm">
  <label>
    Make:
    <input type="text" formControlName="make" />
  </label>
  <label>
    Model:
    <input type="text" formControlName="model" />
  </label>
  <label>
    Year:
    <input type="number" formControlName="year" />
  </label>
  <label>
    Color:
    <input type="text" formControlName="color" />
  </label>
  <label>
    Price:
    <input type="number" formControlName="price" />
  </label>

  <button (click)="doSubmitCar()">{{buttonText}}</button>
</form>
