// angular-demo-app/src/app/car-tool/components/car-edit-row/car-edit-row.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';

import { Car } from '../../models/cars';

@Component({
  selector: '.app-car-edit-row',
  templateUrl: './car-edit-row.component.html',
  styleUrls: ['./car-edit-row.component.css']
})
export class CarEditRowComponent implements OnInit {

  @Input()
  car!: Car;

  @Output()
  saveCar = new EventEmitter<Car>();

  @Output()
  cancelCar = new EventEmitter<void>();

  carForm!: FormGroup;
 
  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.carForm = this.fb.group({
      make: this.car.make,
      model: this.car.model,
      year: this.car.year,
      color: this.car.color,
      price: this.car.price,
    });
  }

  doSaveCar() {
    this.saveCar.emit({
      ...this.carForm.value,
      id: this.car.id,
    } as Car);
  }

  doCancelCar() {
    this.cancelCar.emit();
  }

}

<ng-container [formGroup]="carForm">
  <td>{{car.id}}</td>
  <td><input type="text" formControlName="make" /></td>
  <td><input type="text" formControlName="model" /></td>
  <td><input type="number" formControlName="year" /></td>
  <td><input type="text" formControlName="color" /></td>
  <td><input type="number" formControlName="price" /></td>
  <td>
    <button (click)="doSaveCar()">Save</button>
    <button (click)="doCancelCar()">Cancel</button>
  </td>
</ng-container>

// react-demo-app/src/components/CarEditRow.js
import { useState } from 'react';

export const CarEditRow = ({ car, onSaveCar, onCancelCar: cancelCar }) => {

  const [ carForm, setCarForm ] = useState({
    make: car.make,
    model: car.model,
    year: car.year,
    color: car.color,
    price: car.price,
  });

  const change = (e) => {
    setCarForm({
      ...carForm,
      [ e.target.name ]: e.target.type === 'number' ? parseInt(e.target.value) : e.target.value,
    });
  };

  const saveCar = () => {
    onSaveCar({
      ...carForm,
      id: car.id,
    });
  };


  return (
    <tr>
      <td>{car.id}</td>
      <td><input type="text" name="make"
          value={carForm.make} onChange={change} /></td>
      <td><input type="text" name="model"
          value={carForm.model} onChange={change} /></td>
      <td><input type="number" name="year"
          value={carForm.year} onChange={change} /></td>
      <td><input type="text" name="color"
          value={carForm.color} onChange={change} /></td>
      <td><input type="text" name="price"
          value={carForm.price} onChange={change} /></td>
      <td>
        <button type="button" onClick={saveCar}>Save</button>
        <button type="button" onClick={cancelCar}>Cancel</button>
      </td>
    </tr>
  );  

};
